export const Data = [
  {
    title: "UPSC Integrated Batch",
    id: "1",
    desc: "",

    text: "Features:",
    p1: "Targeted to crack the exam in the first attempt.",
    // p2 "Based on Delhi Pattern.",
    p2: "Weekly prelim and mains test.",
    p3: "Daily prelim and main answer writing session.",
    p4: " Daily The Hindu Editorial Discussion.",
    p5: "Regular Personal guidance and counselling sessions.",
    p6: "Focus on developing the right approach, thought process and application of knowledge.",
  },
  {
    title: "MPSC Integrated Batches",
    id: 2,
    text: "Features:",
    desc: "",

    p1: "Targeted to crack the exam in the first attempt.",
    // p2: " Delhi Pattern  वरती आधारित.",
    p2: "एम सी क्यू ची तयारी करून(5000 Questions)  घेण्यात येईल.",
    p3: "प्रत्येक आठवड्यासweekly test programme.",
    p4: "वैयक्तिक समुपदेशन व मार्गदर्शन.",
    p5: "अभ्यासक्रम शिकवताना  Exam Oriented Systematic Approach.",
    p6: "उत्कृष्ट आणि अनुभवी शिक्षक.",
    p7: "एका बॅच मध्येफक्त 40 ते 45 विद्यार्थी.",
    p8: "वि द्यार्थ्यां चेशंका नि रसन करण्यासाठी Doubt Clearance Sessions.",
    p9: "दररोज Current Affairs Topics वर चर्चा",
    p10: "Quality Enrichment Sessions by Selected Candidates.",
    p11: "मराठी ,English व हि दं ी माध्यमातनू तयारी करून घेणारी टीम.",
    p12: " MPSC Prelims and Mains ची Integrated Approach नेतयारी करून घेण्यात येईल.",
    p13: "* वि षय व घटक नि हाय सराव पेपरची तयारी महत्त्वाच्या वि षयांवर वि शषे कार्यशर्य ाळा.",
  },
  {
    title: "Foundation Batches ",
    id: 3,
    description: "(For both UPSC and MPSC)",
    text: "Features:",

    p1: " ६ वी ते १२ वी पर्यंतच्या पुस्तकांवर आधारित.",
    p2: "UPSC/ MPSC  च्या पूर्व परीक्षेचा संपूर्ण अभ्यासक्रम.",
    p3: "मागील सर्व वर्षांच्या आयोगाच्या प्रश्नपत्रिका आणि दैनंदिन सराव परीक्षा.",
    p4: "यूपीएससीच्या मुलाखतीचा अनुभव असलेले दिल्लीचे तज्ञ मार्गदर्शक.",
    p5: "MPSC / UPSC ची तयारी करणाऱ्या सर्व विद्यार्थ्यांसाठी उपयुक्त.",
    p6: "English, मराठी व हिंदी माध्यमातून मार्गदर्शन.",
    p7: "अभ्यासातील Overall Performance Improvement करणे.",
  },
];
